Reservation page
helio3197/book-a-lawyer-app-frontend pull request #23
Opened 2022-07-17 19:54 UTC by richardoppiyo

In this milestone, I worked on the following:
 - Cancel all active appointments
 - Active appointment:
    -Should include an Cancel btn.
 - Button to edit date (Re-Schedule) (Optional)
 - History:
    -Past appointments (Optional)
   - Canceled appointments (Optional)

2022-07-18 22:11 UTC, helio3197 requested changes
Hi @richardoppiyo :wave: you have made an outstanding job so far congrats! :+1:

**To highlight:** :checkered_flag: 

- No linter errors :heavy_check_mark:
- Professional PR :heavy_check_mark: 
- Clean code :heavy_check_mark:

There are some **required changes** to make your App work better.

**Required changes:**
- Check the comments below

I don't have anything more to tell you other than wish you good luck and happy coding!

2022-07-18 22:11 UTC, helio3197 commented on src/App.js
> +        <Route path="/reservations" element={<Reservations />} />
Currently, the routes for the `Lawyer `and `Reservations` are children of the route with path "/", so for all of their child routes, prepend the "/" in the path prop is not necessary.
```suggestion
        <Route path="lawyers/:id" element={<Lawyer />} />
        <Route path="reservations" element={<Reservations />} />
```

2022-07-18 22:11 UTC, helio3197 commented on src/redux/reservations/deleteReservation.js
> +};
This part is exactly the same as the `reservation.js` reducer, the action types are the same, which may cause unexpected behaviors. A good idea is renaming the action types.
Also a good idea is having an initial status for the state.
```suggestion
const API_RESERVATIONS_DELETE_ENDPOINT = `${process.env.REACT_APP_API_HOST}/api/v1/reservations`;
const REQUEST_STARTED = 'book-a-lawyer/reservationDelete/REQUEST_STARTED';
const REQUEST_FAILED = 'book-a-lawyer/reservationDelete/REQUEST_FAILED';
const REQUEST_COMPLETED = 'book-a-lawyer/reservationDelete/REQUEST_COMPLETED';
const initialState = {
  reservations: [],
  status: 'idle',
};
```

2022-07-18 22:11 UTC, helio3197 commented on src/redux/reservations/deleteReservation.js
> +});
The delete reservation action doesn't return an object, so having a `reservation` parameter is unnecessary.
```suggestion
const requestCompleted = () => ({
  type: REQUEST_COMPLETED,
  payload: {
    status: 'completed',
  },
});
```

2022-07-18 22:11 UTC, helio3197 commented on src/redux/reservations/deleteReservation.js
> +    const response = await fetch(`${API_RESERVATIONS_INDEX_ENDPOINT}/${id}`, {
Update the API endpoint.
```suggestion
    const response = await fetch(`${API_RESERVATIONS_DELETE_ENDPOINT}/${id}`, {
```

2022-07-19 07:09 UTC, richardoppiyo commented
Thank you for the recommendations. I have worked on them.

2022-07-19 17:34 UTC, helio3197 requested changes
Hi @richardoppiyo you have made a good job so far! 👍 

There are some changes to be implemented, please check the comments below.

2022-07-19 17:34 UTC, helio3197 commented on src/redux/reservations/reservations.js
> +});
In the specific case of fetching the reservation_index, we want to keep the list of fetched reservations and it should persist on the state through the session lifetime, having an action for clearing the state in this reducer may cause unnecessary re-fetching the reservations resource every time a component using this reducer is mounted.

```suggestion
```

2022-07-19 17:34 UTC, helio3197 commented on src/redux/reservations/reservations.js
> +const CLEAR_FETCH_STATE = 'book-a-lawyer/reservationsDelete/CLEAR_FETCH_STATE';
As in the comment above having a clear state action on this reducer may be unnecessary.

```suggestion
```

2022-07-19 17:34 UTC, helio3197 commented on src/components/Reservations/Reservations.js
> +import { deleteReservations, clearDeleteReservationState, clearFetchReservationState } from '../../redux/reservations/deleteReservation';
Importing `clearFetchReservationState` may not be necessary here. Please kindly remove it. 

```suggestion
import { deleteReservations, clearDeleteReservationState } from '../../redux/reservations/deleteReservation';
```

2022-07-19 17:34 UTC, helio3197 commented on src/components/Reservations/Reservations.js
> +      dispatch(clearFetchReservationState());
After the component is unmounted, the action for reseting the state should be dispatched.

```suggestion
      dispatch(clearDeleteReservationState());
```

2022-07-19 17:34 UTC, helio3197 commented on src/components/Reservations/Reservations.js
> +  };
Here you are dispatching both actions at the same time, which may cause unexpected behaviors or errors. Please kindly remove that behaviour.
```suggestion
  const deleteReservationData = (id) => () => {
    dispatch(deleteReservations(id));
  };
```

2022-07-19 18:45 UTC, helio3197 approved these changes
Thank you for applying the requested changes 👍

2022-07-19 18:45 UTC, merged